name: Deploy Onramp to EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::223825590112:role/GitHubOnRampDeploy
          aws-region: eu-west-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download & extract bundle (FIXED FOREVER)
        run: |
          curl -fsSL https://github.com/enricoviveri-cyber/onramp-deploy/archive/refs/heads/main.zip -o bundle.zip
          unzip -q bundle.zip
          rsync -av onramp-deploy-main/ ./            # ← questa è l'unica riga che funziona
          rm -rf bundle.zip onramp-deploy-main
          echo "Estratto correttamente:"
          ls -la services/ | head -10

      - name: Build & push all images
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          for dir in services/*/; do
            service=$(basename "$dir")
            if [[ -f "$dir/Dockerfile" ]]; then
              echo "Building onramp-$service"
              docker build -t $REGISTRY/onramp-$service:$TAG "$dir"
              docker push $REGISTRY/onramp-$service:$TAG
            fi
          done

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name onramp-eks --region eu-west-1
          echo "Deploy completato!"

      - name: DONE
        run: echo "TUTTO VERDE! Deploy riuscito."
