name: Deploy Onramp to EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::223825590112:role/GitHubOnRampDeploy
          aws-region: eu-west-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download & extract (NO MORE mv ERROR)
        run: |
          curl -fsSL https://github.com/enricoviveri-cyber/onramp-deploy/archive/refs/heads/main.zip -o repo.zip
          unzip -q repo.zip
          rsync -av onramp-deploy-main/ ./       # ← questa riga risolve tutto
          rm -rf repo.zip onramp-deploy-main
          echo "ESTRAZIONE COMPLETATA:"
          ls -la services/ | head -10

      - name: Build & push all services
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          for svc in services/*/; do
            name=$(basename "$svc")
            if [[ -f "$svc/Dockerfile" ]]; then
              echo "Building onramp-$name:latest"
              docker build -t $REGISTRY/onramp-$name:$TAG "$svc"
              docker push $REGISTRY/onramp-$name:$TAG
            fi
          done

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name onramp-eks --region eu-west-1
          echo "Deploy completato – SHA ${{ github.sha }}"

      - name: SUCCESS
        run: echo "TUTTO VERDE!"
