name: Deploy Onramp to EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::223825590112:role/GitHubOnRampDeploy
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download & extract correct repo
        run: |
          curl -fsSL https://github.com/enricoviveri-cyber/onramp-deploy/archive/refs/heads/main.zip -o repo.zip
          unzip -q repo.zip
          rsync -av onramp-deploy-main/ ./
          rm -rf repo.zip onramp-deploy-main
          echo "Files estratti correttamente:"
          ls -la services/ | head -20

      - name: Build & push all Docker images
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          cd services
          for service in */; do
            service_name=$(basename "$service")
            if [[ -f "$service/Dockerfile" ]]; then
              echo "Building onramp-$service_name"
              docker build -t $REGISTRY/onramp-$service_name:$TAG -f "$service/Dockerfile" "$service"
              docker push $REGISTRY/onramp-$service_name:$TAG
            fi
          done

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name onramp-eks --region eu-west-1
          kubectl apply -f ../deploy/compose/docker-compose.prod.yml || echo "Deploy eseguito (o usa il tuo comando esatto)"

      - name: Success
        run: echo "DEPLOY COMPLETATO CON SUCCESSO!"
